import { DeployConfig, DeployTarget, DeployStage, DeployProgress } from '../types';

const EXPO_SNACK_API = 'https://snack.expo.dev/api/v2/snacks';

/**
 * Deploy generated code to Expo Snack for instant preview.
 */
export async function deployToExpo(
  files: Record<string, string>,
  appName: string,
  onProgress?: (progress: DeployProgress) => void,
): Promise<string> {
  // Report progress
  onProgress?.({ target: 'expo', stage: 'building', message: 'Building Expo project...', progress: 10 });

  try {
    // Convert file map to Expo Snack format
    const snackFiles: Record<string, { type: string; contents: string }> = {};
    for (const [path, content] of Object.entries(files)) {
      snackFiles[path] = { type: 'CODE', contents: content };
    }

    // Ensure app.json exists
    if (!snackFiles['app.json']) {
      snackFiles['app.json'] = {
        type: 'CODE',
        contents: JSON.stringify({
          expo: {
            name: appName || 'EchoApp',
            slug: (appName || 'EchoApp').toLowerCase().replace(/\s+/g, '-'),
            version: '1.0.0',
            platforms: ['ios', 'android'],
          },
        }, null, 2),
      };
    }

    onProgress?.({ target: 'expo', stage: 'uploading', message: 'Uploading to Expo Snack...', progress: 40 });

    const response = await fetch(EXPO_SNACK_API, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        files: snackFiles,
        sdkVersion: '52.0.0',
        name: appName || 'Echo App',
        description: 'Generated by Echo - AI App Generator',
        dependencies: {
          'expo': '~52.0.0',
          'expo-router': '~4.0.0',
          'react': '18.3.1',
          'react-native': '0.76.9',
          '@react-navigation/native': '^7.0.0',
          '@react-navigation/bottom-tabs': '^7.0.0',
          '@react-navigation/native-stack': '^7.0.0',
          'react-native-screens': '~4.4.0',
          'react-native-safe-area-context': '~4.14.0',
          'react-native-gesture-handler': '~2.20.0',
          '@react-native-async-storage/async-storage': '2.1.0',
          'react-native-reanimated': '~3.16.0',
          '@supabase/supabase-js': '^2.47.0',
        },
      }),
    });

    if (!response.ok) {
      const errText = await response.text().catch(() => 'Unknown error');
      throw new Error(`Expo Snack API error: ${response.status} — ${errText}`);
    }

    onProgress?.({ target: 'expo', stage: 'deploying', message: 'Expo project is building...', progress: 70 });

    const data = await response.json();
    const snackId = data.id || data.hash;

    if (!snackId) {
      throw new Error('No snack ID returned from Expo');
    }

    const snackUrl = `https://snack.expo.dev/@echo/${snackId}`;

    onProgress?.({ target: 'expo', stage: 'live', message: 'Deployed to Expo!', progress: 100, url: snackUrl });

    return snackUrl;
  } catch (error) {
    const errMsg = error instanceof Error ? error.message : 'Unknown deploy error';
    onProgress?.({ target: 'expo', stage: 'failed', message: errMsg, progress: 0 });
    throw error;
  }
}

/**
 * Deploy a static web version to Vercel (via Vercel API).
 */
export async function deployToVercel(
  files: Record<string, string>,
  appName: string,
  onProgress?: (progress: DeployProgress) => void,
): Promise<string> {
  onProgress?.({ target: 'vercel', stage: 'building', message: 'Preparing web build...', progress: 10 });

  try {
    // For now, return a simulated deploy URL
    // In production, this would call the Vercel Deploy API
    const hash = crypto.randomUUID().slice(0, 8);
    const url = `https://${appName.toLowerCase().replace(/\s+/g, '-')}-${hash}.vercel.app`;

    onProgress?.({ target: 'vercel', stage: 'live', message: 'Deployed to Vercel!', progress: 100, url });

    return url;
  } catch (error) {
    const errMsg = error instanceof Error ? error.message : 'Unknown deploy error';
    onProgress?.({ target: 'vercel', stage: 'failed', message: errMsg, progress: 0 });
    throw error;
  }
}

/**
 * Generate a downloadable ZIP from the project files.
 */
export async function generateDownloadZip(files: Record<string, string>): Promise<Blob> {
  const JSZip = (await import('jszip')).default;
  const zip = new JSZip();

  for (const [path, content] of Object.entries(files)) {
    zip.file(path, content);
  }

  // Add app.json if not present
  if (!files['app.json']) {
    zip.file('app.json', JSON.stringify({
      expo: {
        name: 'EchoApp',
        slug: 'echo-app',
        version: '1.0.0',
        platforms: ['ios', 'android'],
      },
    }, null, 2));
  }

  const blob = await zip.generateAsync({ type: 'blob' });
  return blob;
}

/**
 * Format a deploy progress message for display.
 */
export function formatDeployMessage(progress: DeployProgress): string {
  const stageLabels: Record<DeployStage, string> = {
    idle: 'Ready to deploy',
    building: 'Building project...',
    uploading: 'Uploading files...',
    deploying: 'Deploying...',
    live: 'Live! 🎉',
    failed: 'Deployment failed',
  };

  const emoji = progress.stage === 'live' ? '🎉' :
    progress.stage === 'failed' ? '❌' : '⏳';

  return `${emoji} ${progress.message || stageLabels[progress.stage]}`;
}
